// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnbSjZIvWb3ZoLkxqGhP8Qdcpk6V2zpEA',
    appId: '1:823959875719:web:97a0288f6064d3221fc822',
    messagingSenderId: '823959875719',
    projectId: 'dapp03-f1ab1',
    authDomain: 'dapp03-f1ab1.firebaseapp.com',
    storageBucket: 'dapp03-f1ab1.firebasestorage.app',
    measurementId: 'G-2P60FQQGKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK6ve9adi0fzoydH4E4ANgd3yek36D0vY',
    appId: '1:823959875719:android:47e4369a6a4f42ba1fc822',
    messagingSenderId: '823959875719',
    projectId: 'dapp03-f1ab1',
    storageBucket: 'dapp03-f1ab1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRnWaKS011NZi6AEb6t0FUbCBzqXeEH38',
    appId: '1:823959875719:ios:bc1bfabb5db5a9d41fc822',
    messagingSenderId: '823959875719',
    projectId: 'dapp03-f1ab1',
    storageBucket: 'dapp03-f1ab1.firebasestorage.app',
    iosBundleId: 'com.example.rareDiseaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRnWaKS011NZi6AEb6t0FUbCBzqXeEH38',
    appId: '1:823959875719:ios:bc1bfabb5db5a9d41fc822',
    messagingSenderId: '823959875719',
    projectId: 'dapp03-f1ab1',
    storageBucket: 'dapp03-f1ab1.firebasestorage.app',
    iosBundleId: 'com.example.rareDiseaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnbSjZIvWb3ZoLkxqGhP8Qdcpk6V2zpEA',
    appId: '1:823959875719:web:50e08adf4df162751fc822',
    messagingSenderId: '823959875719',
    projectId: 'dapp03-f1ab1',
    authDomain: 'dapp03-f1ab1.firebaseapp.com',
    storageBucket: 'dapp03-f1ab1.firebasestorage.app',
    measurementId: 'G-3DC8SXEB8L',
  );
}
